# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dipendente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from VistaCreanuovodipendente import Ui_Form


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 622)
        MainWindow.setStyleSheet("\n"
                                 "background-color: rgb(255, 255, 255);")
        self.OrangeBand = QtWidgets.QLabel(MainWindow)
        self.OrangeBand.setGeometry(QtCore.QRect(20, 10, 911, 51))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.OrangeBand.setFont(font)
        self.OrangeBand.setStyleSheet("background-color: rgba(0, 150, 255, 219);\n"
                                      "background-color: rgba(0, 150, 255, 177);\n"
                                      "background-color: rgba(255, 147, 0, 242);\n"
                                      "background-color: rgb(245, 148, 1);\n"
                                      "font: 13pt \".AppleSystemUIFont\";\n"
                                      "border-radius: 16px;\n"
                                      "\n"
                                      "")
        self.OrangeBand.setText("")
        self.OrangeBand.setObjectName("OrangeBand")
        self.textBrowser = QtWidgets.QTextBrowser(MainWindow)
        self.textBrowser.setGeometry(QtCore.QRect(530, 10, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(MainWindow)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 20, 256, 51))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                         "font: 13pt \".AppleSystemUIFont\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushHome = QtWidgets.QPushButton(MainWindow)
        self.pushHome.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.pushHome.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushHome.setText("")
        self.pushHome.setObjectName("pushHome")
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(190, 220, 271, 161))
        self.line.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                "border-color: rgb(0, 0, 0);\n"
                                "color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 150, 151, 51))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 390, 151, 51))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 38, 0);\n"
                                        "background-color: rgba(255, 255, 255, 0);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 721, 521))
        self.label_3.setStyleSheet("border-radius: 18px;\n"
                                   "background-color: rgb(235, 235, 235);\n"
                                   "")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textListaDeiDipendenti = QtWidgets.QTextBrowser(MainWindow)
        self.textListaDeiDipendenti.setGeometry(QtCore.QRect(230, 80, 411, 61))
        self.textListaDeiDipendenti.setStyleSheet("font: 13pt \".AppleSystemUIFont\";\n"
                                                  "\n"
                                                  "background-color: rgba(255, 255, 255, 0);")
        self.textListaDeiDipendenti.setObjectName("textListaDeiDipendenti")
        self.listWidget = QtWidgets.QListWidget(MainWindow)
        self.listWidget.setGeometry(QtCore.QRect(230, 130, 271, 141))
        self.listWidget.setStyleSheet("background-color: rgba(215, 131, 255, 0);\n"
                                      "background-color: rgb(235, 235, 235);\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "border-radius: 17px;\n"
                                      "")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.verticalSlider = QtWidgets.QSlider(MainWindow)
        self.verticalSlider.setGeometry(QtCore.QRect(460, 137, 21, 131))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.textYear_blue = QtWidgets.QTextBrowser(MainWindow)
        self.textYear_blue.setGeometry(QtCore.QRect(45, 540, 131, 51))
        self.textYear_blue.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textYear_blue.setObjectName("textYear_blue")
        self.label_blue = QtWidgets.QLabel(MainWindow)
        self.label_blue.setGeometry(QtCore.QRect(20, 70, 181, 391))
        self.label_blue.setStyleSheet("background-color: rgba(0, 145, 147, 203);\n"
                                      "background-color: rgba(0, 145, 147, 154);\n"
                                      "background-color: rgb(148, 33, 147);\n"
                                      "background-color: rgba(83, 27, 147, 242);\n"
                                      "background-color: rgb(0, 150, 255);\n"
                                      "background-color: rgb(0, 143, 248);\n"
                                      "border-radius:18px;")
        self.label_blue.setText("")
        self.label_blue.setObjectName("label_blue")
        self.pushPianoDiLavoro = QtWidgets.QPushButton(MainWindow)
        self.pushPianoDiLavoro.setGeometry(QtCore.QRect(30, 150, 161, 51))
        self.pushPianoDiLavoro.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                             "font: 700 18pt \"SF Pro\";\n"
                                             "color: rgb(255, 255, 255);")
        self.pushPianoDiLavoro.setObjectName("pushPianoDiLavoro")
        self.pushContabilita = QtWidgets.QPushButton(MainWindow)
        self.pushContabilita.setGeometry(QtCore.QRect(19, 330, 151, 51))
        self.pushContabilita.setStyleSheet("background-color: rgb(255, 38, 0);\n"
                                           "background-color: rgba(255, 255, 255, 0);\n"
                                           "font: 700 18pt \"SF Pro\";\n"
                                           "color: rgb(255, 255, 255);")
        self.pushContabilita.setObjectName("pushContabilita")
        self.pushClienti = QtWidgets.QPushButton(MainWindow)
        self.pushClienti.setGeometry(QtCore.QRect(-7, 270, 151, 51))
        self.pushClienti.setStyleSheet("background-color: rgb(255, 38, 0);\n"
                                       "background-color: rgba(255, 255, 255, 0);\n"
                                       "\n"
                                       "font: 700 18pt \"SF Pro\";\n"
                                       "color: rgb(255, 255, 255);")
        self.pushClienti.setObjectName("pushClienti")
        self.textDay_blue = QtWidgets.QTextBrowser(MainWindow)
        self.textDay_blue.setGeometry(QtCore.QRect(56, 470, 111, 71))
        self.textDay_blue.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textDay_blue.setObjectName("textDay_blue")
        self.pushStatistiche = QtWidgets.QPushButton(MainWindow)
        self.pushStatistiche.setGeometry(QtCore.QRect(15, 390, 151, 51))
        self.pushStatistiche.setStyleSheet("background-color: rgb(255, 38, 0);\n"
                                           "background-color: rgba(255, 255, 255, 0);\n"
                                           "font: 700 18pt \"SF Pro\";\n"
                                           "color: rgb(255, 255, 255);")
        self.pushStatistiche.setObjectName("pushStatistiche")
        self.label_lightblue = QtWidgets.QLabel(MainWindow)
        self.label_lightblue.setGeometry(QtCore.QRect(20, 470, 181, 121))
        self.label_lightblue.setStyleSheet("background-color: rgba(255, 147, 0, 103);\n"
                                           "background-color: rgba(255, 147, 0, 154);\n"
                                           "background-color: rgba(118, 214, 255, 242);\n"
                                           "background-color: rgb(140, 232, 232);\n"
                                           "background-color: rgb(118, 214, 255);\n"
                                           "background-color: rgb(145, 234, 255);\n"
                                           "background-color: rgb(126, 221, 255);\n"
                                           "border-radius: 17px;")
        self.label_lightblue.setText("")
        self.label_lightblue.setObjectName("label_lightblue")
        self.pushDipendenti = QtWidgets.QPushButton(MainWindow)
        self.pushDipendenti.setGeometry(QtCore.QRect(-2, 90, 181, 51))
        self.pushDipendenti.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
                                          "background-color: rgba(255, 255, 255, 0);\n"
                                          "font: 700 18.2pt \"SF Pro\";")
        self.pushDipendenti.setObjectName("pushDipendenti")
        self.pushMagazzino = QtWidgets.QPushButton(MainWindow)
        self.pushMagazzino.setGeometry(QtCore.QRect(18, 210, 141, 51))
        self.pushMagazzino.setStyleSheet("background-color: rgb(255, 38, 0);\n"
                                         "background-color: rgba(255, 255, 255, 0);\n"
                                         "font: 700 18pt \"SF Pro\";\n"
                                         "color: rgb(255, 255, 255);")
        self.pushMagazzino.setObjectName("pushMagazzino")
        self.textMonth_blue = QtWidgets.QTextBrowser(MainWindow)
        self.textMonth_blue.setGeometry(QtCore.QRect(45, 520, 131, 41))
        self.textMonth_blue.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textMonth_blue.setObjectName("textMonth_blue")
        self.pushButton_12 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_12.setGeometry(QtCore.QRect(520, 140, 111, 31))
        self.pushButton_12.setStyleSheet("border-radius: 8px\n"
                                         "")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 220, 111, 31))
        self.pushButton_13.setStyleSheet("border-radius: 8px\n"
                                         "")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_11.setGeometry(QtCore.QRect(660, 160, 121, 61))
        self.pushButton_11.setStyleSheet("border-radius: 8px\n"
                                         "")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_14 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_14.setGeometry(QtCore.QRect(520, 180, 111, 31))
        self.pushButton_14.setStyleSheet("border-radius: 8px\n"
                                         "")
        self.pushButton_14.setObjectName("pushButton_14")
        self.OrangeBand.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushHome.raise_()
        self.line.raise_()
        self.pushButton_3.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.textListaDeiDipendenti.raise_()
        self.listWidget.raise_()
        self.verticalSlider.raise_()
        self.label_blue.raise_()
        self.pushPianoDiLavoro.raise_()
        self.pushContabilita.raise_()
        self.pushClienti.raise_()
        self.pushStatistiche.raise_()
        self.label_lightblue.raise_()
        self.pushDipendenti.raise_()
        self.pushMagazzino.raise_()
        self.textDay_blue.raise_()
        self.textYear_blue.raise_()
        self.textMonth_blue.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_11.raise_()
        self.pushButton_14.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:696; color:#ffffff;\">LaGiuseppina</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:696; color:#ffffff;\">HOME</span></p></body></html>"))
        self.textListaDeiDipendenti.setHtml(_translate("MainWindow",
                                                       "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                       "p, li { white-space: pre-wrap; }\n"
                                                       "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt; font-weight:696; color:#000000;\">LISTA DEI DIPENDENTI</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "   Dipendente 1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "   Dipendente 2"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "   Dipendente 3"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "   Dipendente 4"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "   Dipendente 5"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.textYear_blue.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:33pt; font-weight:696; color:#ffffff;\">2021</span></p></body></html>"))
        self.pushPianoDiLavoro.setText(_translate("MainWindow", "PIANO DI LAVORO"))
        self.pushContabilita.setText(_translate("MainWindow", "CONTABILITA\'"))
        self.pushClienti.setText(_translate("MainWindow", "CLIENTI"))
        self.textDay_blue.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                             "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:696; color:#ffffff;\">17</span></p></body></html>"))
        self.pushStatistiche.setText(_translate("MainWindow", "STATISTICHE"))
        self.pushDipendenti.setText(_translate("MainWindow", "DIPENDENTI"))
        self.pushMagazzino.setText(_translate("MainWindow", "MAGAZZINO"))
        self.textMonth_blue.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21pt; font-weight:696; color:#ffffff;\">MAGGIO</span></p></body></html>"))
        self.pushButton_12.setText(_translate("MainWindow", "Visualizza"))
        self.pushButton_13.setText(_translate("MainWindow", "Elimina"))
        self.pushButton_11.setText(_translate("MainWindow", "Crea un \n"
                                                            "nuovo\n"
                                                            "dipendente"))
        self.pushButton_14.setText(_translate("MainWindow", "Modifica"))
        self.pushButton_11.clicked.connect(self.vista_creanuovodipendente)
    def vista_creanuovodipendente(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
