# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Creanuovodipendente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 622)
        Form.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 911, 51))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 150, 255, 219);\n"
"background-color: rgba(0, 150, 255, 177);\n"
"background-color: rgba(255, 147, 0, 242);\n"
"background-color: rgb(245, 148, 1);\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-radius: 16px;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(530, 10, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 20, 256, 51))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 13pt \".AppleSystemUIFont\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(190, 220, 271, 161))
        self.line.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 150, 151, 51))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 390, 151, 51))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 38, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 721, 521))
        self.label_3.setStyleSheet("border-radius: 18px;\n"
"background-color: rgb(235, 235, 235);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textBrowser_12 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_12.setGeometry(QtCore.QRect(230, 80, 411, 61))
        self.textBrowser_12.setStyleSheet("font: 13pt \".AppleSystemUIFont\";\n"
"\n"
"background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(230, 130, 271, 141))
        self.listWidget.setStyleSheet("background-color: rgba(215, 131, 255, 0);\n"
"background-color: rgb(235, 235, 235);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 17px;\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setGeometry(QtCore.QRect(460, 137, 21, 131))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(230, 338, 391, 231))
        self.label_5.setStyleSheet("border-radius: 18px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(372, 418, 61, 31))
        self.spinBox_2.setStyleSheet("border-radius: 13px;\n"
"background-color: rgb(83, 27, 147);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.spinBox_2.setProperty("value", 0)
        self.spinBox_2.setObjectName("spinBox_2")
        self.textBrowser_23 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_23.setGeometry(QtCore.QRect(252, 532, 111, 31))
        self.textBrowser_23.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_23.setObjectName("textBrowser_23")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(322, 530, 271, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(83, 27, 147);\n"
"border-radius: 13px;\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(372, 382, 61, 31))
        self.spinBox.setStyleSheet("border-radius: 13px;\n"
"background-color: rgb(83, 27, 147);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(312, 493, 281, 31))
        self.lineEdit.setStyleSheet("border-radius: 13px;\n"
"background-color: rgb(83, 27, 147);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser_22 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_22.setGeometry(QtCore.QRect(252, 495, 111, 31))
        self.textBrowser_22.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_22.setObjectName("textBrowser_22")
        self.textBrowser_24 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_24.setGeometry(QtCore.QRect(252, 349, 111, 31))
        self.textBrowser_24.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_24.setObjectName("textBrowser_24")
        self.textBrowser_25 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_25.setGeometry(QtCore.QRect(252, 457, 141, 41))
        self.textBrowser_25.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_25.setObjectName("textBrowser_25")
        self.textBrowser_26 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_26.setGeometry(QtCore.QRect(252, 384, 171, 51))
        self.textBrowser_26.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_26.setObjectName("textBrowser_26")
        self.textBrowser_27 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_27.setGeometry(QtCore.QRect(252, 420, 121, 31))
        self.textBrowser_27.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_27.setObjectName("textBrowser_27")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(312, 345, 291, 31))
        self.lineEdit_4.setStyleSheet("border-radius: 13px;\n"
"\n"
"background-color: rgb(148, 55, 255);\n"
"background-color: rgb(215, 131, 255);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(146, 146, 146);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(382, 455, 211, 31))
        self.lineEdit_3.setStyleSheet("border-radius: 13px;background-color: rgb(83, 27, 147);\n"
"background-color: rgb(122, 129, 255);\n"
"background-color: rgb(235, 235, 235);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(638, 530, 131, 41))
        self.pushButton_8.setStyleSheet("border-radius: 18px;\n"
"background-color: rgb(235, 235, 235);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.textBrowser_11 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_11.setGeometry(QtCore.QRect(45, 540, 131, 51))
        self.textBrowser_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 181, 391))
        self.label_2.setStyleSheet("background-color: rgba(0, 145, 147, 203);\n"
"background-color: rgba(0, 145, 147, 154);\n"
"background-color: rgb(148, 33, 147);\n"
"background-color: rgba(83, 27, 147, 242);\n"
"background-color: rgb(0, 150, 255);\n"
"background-color: rgb(0, 143, 248);\n"
"border-radius:18px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 150, 161, 51))
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"SF Pro\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(19, 330, 151, 51))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 38, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"SF Pro\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(-7, 270, 151, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 38, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"font: 700 18pt \"SF Pro\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser_9 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_9.setGeometry(QtCore.QRect(56, 470, 111, 71))
        self.textBrowser_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(15, 390, 151, 51))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 38, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"SF Pro\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 470, 181, 121))
        self.label_4.setStyleSheet("background-color: rgba(255, 147, 0, 103);\n"
"background-color: rgba(255, 147, 0, 154);\n"
"background-color: rgba(118, 214, 255, 242);\n"
"background-color: rgb(140, 232, 232);\n"
"background-color: rgb(118, 214, 255);\n"
"background-color: rgb(145, 234, 255);\n"
"background-color: rgb(126, 221, 255);\n"
"border-radius: 17px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(-2, 90, 181, 51))
        self.pushButton_2.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18.2pt \"SF Pro\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(18, 210, 141, 51))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 38, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"SF Pro\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_29 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_29.setGeometry(QtCore.QRect(45, 520, 131, 41))
        self.textBrowser_29.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_29.setObjectName("textBrowser_29")
        self.textBrowser_21 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_21.setGeometry(QtCore.QRect(290, 300, 451, 51))
        self.textBrowser_21.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(660, 160, 121, 61))
        self.pushButton_11.setStyleSheet("border-radius: 8px\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(520, 140, 111, 31))
        self.pushButton_12.setStyleSheet("border-radius: 8px\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 220, 111, 31))
        self.pushButton_13.setStyleSheet("border-radius: 8px\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(520, 180, 111, 31))
        self.pushButton_14.setStyleSheet("border-radius: 8px\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton.raise_()
        self.line.raise_()
        self.pushButton_3.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.textBrowser_12.raise_()
        self.listWidget.raise_()
        self.verticalSlider.raise_()
        self.label_5.raise_()
        self.spinBox_2.raise_()
        self.textBrowser_23.raise_()
        self.lineEdit_2.raise_()
        self.spinBox.raise_()
        self.lineEdit.raise_()
        self.textBrowser_22.raise_()
        self.textBrowser_24.raise_()
        self.textBrowser_25.raise_()
        self.textBrowser_26.raise_()
        self.textBrowser_27.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_8.raise_()
        self.label_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_5.raise_()
        self.pushButton_9.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_10.raise_()
        self.textBrowser_9.raise_()
        self.textBrowser_11.raise_()
        self.textBrowser_29.raise_()
        self.textBrowser_21.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:696; color:#ffffff;\">Frutta&amp;Verdura</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:696; color:#ffffff;\">HOME</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:30pt; font-weight:696; color:#000000;\">LISTA DEI DIPENDENTI</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "   Dipendente 1"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "   Dipendente 2"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "   Dipendente 3"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "   Dipendente 4"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "   Dipendente 5"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.textBrowser_23.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Telefono</span></p></body></html>"))
        self.textBrowser_22.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">E-mail</span></p></body></html>"))
        self.textBrowser_24.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Nome </span></p></body></html>"))
        self.textBrowser_25.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Tipo di contratto</span></p></body></html>"))
        self.textBrowser_26.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Ore settimanali</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.textBrowser_27.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Paga ad ora (€ )</span></p></body></html>"))
        self.pushButton_8.setText(_translate("Form", "Salva le modifiche"))
        self.textBrowser_11.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:33pt; font-weight:696; color:#ffffff;\">2021</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "PIANO DI LAVORO"))
        self.pushButton_6.setText(_translate("Form", "CONTABILITA\'"))
        self.pushButton_5.setText(_translate("Form", "CLIENTI"))
        self.textBrowser_9.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:696; color:#ffffff;\">17</span></p></body></html>"))
        self.pushButton_9.setText(_translate("Form", "STATISTICHE"))
        self.pushButton_2.setText(_translate("Form", "DIPENDENTI"))
        self.pushButton_10.setText(_translate("Form", "MAGAZZINO"))
        self.textBrowser_29.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21pt; font-weight:696; color:#ffffff;\">MAGGIO</span></p></body></html>"))
        self.textBrowser_21.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21pt; font-weight:696; color:#000000;\">Crea un nuovo dipendente!</span></p></body></html>"))
        self.pushButton_11.setText(_translate("Form", "Crea un \n"
"nuovo\n"
"dipendente"))
        self.pushButton_12.setText(_translate("Form", "Visualizza"))
        self.pushButton_13.setText(_translate("Form", "Elimina"))
        self.pushButton_14.setText(_translate("Form", "Modifica"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec())